---
abstract: "Nasty tools for probing Dist::Zilla's internal state."
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: '1.003001'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::DZil: '0'
  Test::Fatal: '0.003'
  Test::More: '0.96'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Util-EmulatePhase
provides:
  Dist::Zilla::Util::EmulatePhase:
    file: lib/Dist/Zilla/Util/EmulatePhase.pm
    version: '1.001002'
  Dist::Zilla::Util::EmulatePhase::PrereqCollector:
    file: lib/Dist/Zilla/Util/EmulatePhase/PrereqCollector.pm
    version: '1.001002'
recommends:
  Moose: '2.000'
requires:
  Carp: '0'
  Dist::Zilla::Prereqs: '0'
  Hash::Merge::Simple: '0'
  Moose: '0'
  Scalar::Util: '0'
  Sub::Exporter: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Util-EmulatePhase/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Util-EmulatePhase
  repository: https://github.com/kentnl/Dist-Zilla-Util-EmulatePhase.git
version: '1.001002'
